declare module "*.jpg";
declare module "*.png";
declare module "*.svg";
declare module "*.json";
declare module "*.css";
declare module "*.mp3";
declare module "*.ogg";
declare module "*.ttf";
declare module "*.wav";
